### PR TITLE
Update version to release 1.7.3

### PR DESCRIPTION
**Pull request by zhang-alvin**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This PR is to address issue https://github.com/erdc/proteus/issues/1082.

### CODE REVIEW

**Comment by zhang-alvin** [comment]
@conda-forge-admin, please rerender

**Comment by davidbrochart** [comment]
@zhang-alvin file `proteus/tests/levelset/vortex/vortex_c0p1cg_bdf_2_level_1_expected.h5` doesn't exist, should it be removed from `setup.py`?

**Comment by zhang-alvin** [comment]
> @zhang-alvin file `proteus/tests/levelset/vortex/vortex_c0p1cg_bdf_2_level_1_expected.h5` doesn't exist, should it be removed from `setup.py`?

Yes, that sounds right. I'll take care of removing the .h5 file references as part of https://github.com/erdc/proteus/pull/1077.

**Comment by tridelat** [comment]
@zhang-alvin for my current conda install of Proteus, it looks like the LICENSE.md file is packaged in `$MY_CONDA_INSTALL_DIR/pkgs/proteus-1.7.1-mpi_mpich_h43e24ae_9/info/licenses/LICENSE.md`
I don't know if this kind of file is added automatically or explicitly, @davidbrochart ?

**Comment by cekees** [comment]
@tridelat it should be the same as proteus/LICENSE.md

**Comment by davidbrochart** [comment]
@tridelat this location is where conda downloads packages and caches them. It basically consists of the feedstock recipe. It has nothing to do with your installation location.

**Comment by tridelat** [comment]
@cekees yes, it is the same as proteus/LICENSE.md.
@davidbrochart I see, the license file is also in `$MY_CONDA_DIR/lib/python3.7/site-packages/proteus-1.7.1.dist-info/LICENSE.md`.  Not sure if that is enough for @zhang-alvin checklist in terms of ensuring that the license is packaged

**Comment by davidbrochart** [comment]
Thanks @zhang-alvin!

**Pull request merged**
