### PR TITLE
Revive #20 (OS X build)

### PR DESCRIPTION
**Pull request by davidbrochart**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by zhang-alvin** [comment]
@davidbrochart I'm fine with the updates/changes, but I'm not sure what's happening with the build error:
```
ModuleNotFoundError: No module named 'conda_forge_ci_setup'
```
Do you have a sense why this is happening?

**Comment by davidbrochart** [comment]
No, this is weird. And it doesn't create a job for OSX either.
I wanted to check if things had changed and if we could build Proteus for OSX. Is there a need for that on your side?

**Comment by zhang-alvin** [comment]
I think it'd be nice to have a working recipe for OSX. At the moment, the linux recipe is outdated by a couple of versions, but at least it's functional.

**Comment by davidbrochart** [comment]
@conda-forge-admin, please rerender

**Comment by cekees** [comment]
osx builds are working on azure now

**Pull request closed without merging**
