### PR TITLE
Osx support

### PR DESCRIPTION
**Pull request by davidbrochart**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by cekees** [comment]
@davidbrochart @ejtovar has a fix involving one of the proteus pxd files that fixes the osx build. It should go into the next proteus release.

**Comment by davidbrochart** [comment]
That's great news! Do you have a link pointing to the CI where I can see that?

**Comment by cekees** [comment]
@ejtovar is going to put up a proteus PR. We will need to enable an osx/conda build environment on travis in that PR, but it won't build properly without some hacks disabling chrono. I was going to see about getting those upstream chrono changes merged in.

**Comment by davidbrochart** [comment]
I see, I thought we had chrono working on OSX with conda-forge. I think they are going to release v5.0.0 soon, maybe this will be a good time to go back to that issue.

**Comment by ejtovar** [comment]
Hi David,

Here is the PR with the small fix: https://github.com/erdc/proteus/pull/1083

**Comment by cekees** [comment]
Builds are working on azure now. Thanks for looking at this @davidbrochart and @ejtovar .

**Pull request closed without merging**
