### PR TITLE
remove pins already specified in conda_build_config (updated)

### PR DESCRIPTION
**Pull request by cekees**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by cekees** [comment]
@conda-forge-admin, please rerender

**Comment by cekees** [comment]
@minrk  I'm at a bit of a loss and wondered if you could make a suggestion. All the openmpi builds fail on this feedstock, seemingly because there is no scorec build with openmpi 4 and metis 5.1.0. I'm not sure where the openmpi 4.* requirement is coming from, but I have enabled/forced the scorec-feedstock to do a variant with metis 5.1.0 (and openmpi). I guess I may need to force a scorec openmpi 4 variant.   

```
├─ hdf5 *,1.14.3.* mpi_openmpi_* is installable with the potential options
│  ├─ hdf5 1.14.3 would require
│  │  └─ openmpi >=4.1.6,<5.0a0 , which requires
│  │     └─ mpi 1.0 openmpi, which can be installed;
│  └─ hdf5 1.14.3 would require
│     └─ openmpi >=5.0.3,<6.0a0 , which conflicts with any installable versions previously reported;
├─ metis 5.1.0.*  is requested and can be installed;
├─ openmpi 4.* , which can be installed (as previously explained);
└─ scorec >=2.2.8  is not installable because there are no viable options
   ├─ scorec 2.2.8 would require
   │  └─ mpich >=4.2.2,<5.0a0 , which requires
   │     └─ mpi 1.0 mpich, which conflicts with any installable versions previously reported;
   ├─ scorec 2.2.8 would require
   │  └─ metis >=5.1.1,<5.1.2.0a0 , which conflicts with any installable versions previously reported;
   ├─ scorec 2.2.8 would require
   │  └─ openmpi >=5.0.5,<6.0a0 , which conflicts with any installable versions previously reported;
   └─ scorec 2.2.8 would require
      └─ metis >=5.2.1,<5.2.2.0a0 , which conflicts with any installable versions previously reported.
```

**Comment by minrk** [comment]
I believe it's because the openmpi 5 migration hasn't completed so openmpi 4 is the default, but scorec 2.2.8 was built after being migrated to openmpi 5, so there is no openmpi 4 build of scorec >=2.2.8.

The simplest solution is probably to manually apply the openmpi 5 migration here (manual migration means dropping the `opempi5.yaml` file in `.ci_support/migrations/` and rerendering), which I've done.

**Comment by cekees** [comment]
Thanks @minrk!

**Pull request merged**
